name: learn-github-actions
on: [push]
jobs:
  basic-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - run: dotnet --version
